-- --TABELA
-- INSERT INTO TBL_FORNECIMENTO
-- VALUES(04, 0004, 02, 220);

-- --INSERÇÃO DE DADOS(DML - COMANDO INSERT)
-- INSERT INTO fornecedor
-- VALUES(DEFAULT,'Kalunga', DEFAULT, '1930234066');

--REMOVENDO REFERENCIA INCOMPLETA DE UMA FJ NA TABELA FORNECEDORES
ALTER TABLE fornecedor DROP CONSTRAINT ccod CASCADE;
--REMOVENDO REFERENCIA INCOMPLETA DE UMA FJ NA TABELA PECA
ALTER TABLE peca DROP CONSTRAINT ccod CASCADE;
--REMOVENDO REFERENCIA INCOMPLETA DE UMA FJ NA TABELA PROJETO
ALTER TABLE projeto DROP CONSTRAINT ccod CASCADE;
--CRIANDO A FK CCOD EM FORNECEDOR
ALTER TABLE fornecedor
ADD CONSTRAINT ccod FOREIGN KEY (ccod) REFERENCES cidade(ccod);
--CRIANDO A FK CCOD NA TABELA PECA
ALTER TABLE peca
ADD CONSTRAINT ccod FOREIGN KEY (ccod) REFERENCES cidade(ccod);
--ADICIONANDO O CAMPO FK CCOD NA TABELA PROJETO
ALTER TABLE projeto
ADD CONSTRAINT ccod FOREIGN KEY (ccod) REFERENCES cidade(ccod);

SELECT * FROM FORNECEDOR;
SELECT * FROM PECA;
SELECT * FROM PROJETO;




